name: aerospike-admin

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-admin:manylinux

build:
  - name: build
    environment:
      PYTHONS: /opt/python/cp34-cp34m/bin,/opt/python/cp35-cp35m/bin,/opt/python/cp36-cp36m/bin,/opt/python/cp37-cp37m/bin,/opt/python/cp38-cp38/bin
    script:
      - make
    artifact:
      - /work/source/build/bin/asadm
